//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCopilot2.Domain.Resources.Enums.DataTypes {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotationsDataTypeResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationsDataTypeResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevCopilot2.Domain.Resources.Enums.DataTypes.DataAnnotationsDataTypeResources", typeof(DataAnnotationsDataTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text
        /// </summary>
        public static string Text
        {
            get
            {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Url
        /// </summary>
        public static string Url
        {
            get
            {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Password
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber
        /// </summary>
        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NationalCode
        /// </summary>
        public static string NationalCode
        {
            get
            {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PersianDate
        /// </summary>
        public static string PersianDate
        {
            get
            {
                return ResourceManager.GetString("PersianDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price
        /// </summary>
        public static string Price
        {
            get
            {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color
        /// </summary>
        public static string Color
        {
            get
            {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Image
        /// </summary>
        public static string Image
        {
            get
            {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video
        /// </summary>
        public static string Video
        {
            get
            {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File
        /// </summary>
        public static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Others
        /// </summary>
        public static string Others
        {
            get
            {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List
        /// </summary>
        public static string List
        {
            get
            {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DtoList
        /// </summary>
        public static string DtoList
        {
            get
            {
                return ResourceManager.GetString("DtoList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hidden
        /// </summary>
        public static string Hidden
        {
            get
            {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
    }
}
