//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCopilot2.Domain.Resources.DTOs.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseListDtoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseListDtoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevCopilot2.Domain.Resources.DTOs.Common.BaseListDtoResources", typeof(BaseListDtoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Id
        {
            get
            {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string CreateDate
        {
            get
            {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string LatestEditDate
        {
            get
            {
                return ResourceManager.GetString("LatestEditDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string EditCounts
        {
            get
            {
                return ResourceManager.GetString("EditCounts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string AuthorId
        {
            get
            {
                return ResourceManager.GetString("AuthorId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string AuthorName
        {
            get
            {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string BaseSortEntityType
        {
            get
            {
                return ResourceManager.GetString("BaseSortEntityType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string SortType
        {
            get
            {
                return ResourceManager.GetString("SortType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string FromDate
        {
            get
            {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string ToDate
        {
            get
            {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string RequiredErrorMessage
        {
            get
            {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string IsNotValidErrorMessage
        {
            get
            {
                return ResourceManager.GetString("IsNotValidErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string MinLengthErrorMessage
        {
            get
            {
                return ResourceManager.GetString("MinLengthErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string MaxLengthErrorMessage
        {
            get
            {
                return ResourceManager.GetString("MaxLengthErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string RangeErrorMessage
        {
            get
            {
                return ResourceManager.GetString("RangeErrorMessage", resourceCulture);
            }
        }
    }
}
